a=float(input('aantal 1 cent')) * 1
b=float(input('aantal 2 cent')) * 2
c=float(input('aantal 5 cent')) * 5
d=float(input('aantal 10 cent')) * 10
e=float(input('aantal 20 cent')) * 20
som=a + b + c + d + e
euro=c // 100
tienc= (som % 100) // 10
eenc= som %10
print("You have ", euro, ".", tienc, eenc, " euro!", sep="")re