a=input("number of 1 eurocent coins: ")
a=float(a)
b=input("number of 2 eurocent coins: ")
b=float(b)
c=input("number of 5 eurocent coins: ")
c=float(c)
d=input("number of 10 eurocent coins: ")
d=float(d)
e=input("number of 20 eurocent coins: ")
e=float(e)
euro=(1*a+2*b+5*c+10*d+20*e)/100
print("You have ", euro,"euro.")