total = int(input("amount? "))
twoeuros = (total // 200)
oneeuros = ((total - twoeuros * 200) // 100)
fiftyc = ((total - twoeuros * 200 - oneeuros * 100) // 50)
twentyc = ((total - twoeuros * 200 - oneeuros * 100 - fiftyc * 50) // 20)
tenc = ((total - twoeuros * 200 - oneeuros * 100 - fiftyc * 50 - twentyc * 20) // 10)
fivec = ((total - twoeuros * 200 - oneeuros * 100 - fiftyc * 50 - twentyc * 20 - tenc * 10) // 5)
twoc = ((total - twoeuros * 200 - oneeuros * 100 - fiftyc * 50 - twentyc * 20 - tenc * 10 - fivec * 5) // 2)
onec = (total - twoeuros * 200 - oneeuros * 100 - fiftyc * 50 - twentyc * 20 - tenc * 10 - fivec * 5 - twoc * 2)

twoeuros = str(twoeuros)
oneeuros = str(oneeuros)
fiftyc = str(fiftyc)
twentyc = str(twentyc)
tenc = str(tenc)
fivec = str(fivec)
twoc = str(twoc)
onec = str(onec)

print("2-euros: " + twoeuros)
print("1-euros: " + oneeuros)
print("50c-euros: " + fiftyc)
print("20c-euros: " + twentyc)
print("10c-euros: " + tenc)
print("5c-euros: " + fivec)
print("2c-euros: " + twoc)
print("1c-euros: " + onec)