amount = int(input())

twoEuro, rest = divmod(amount, 200)
oneEuro, rest = divmod(rest, 100)
fiftyCent, rest = divmod(rest, 50)
twentyCent, rest = divmod(rest, 20)
tenCent, rest = divmod(rest, 10)
fiveCent, rest = divmod(rest, 5)
secondCent, rest = divmod(rest, 2)
oneCent, rest = divmod(rest, 1)

print("2-euros: " + str(twoEuro)
print("1-euros: " + str(oneEuro))
print("50c-euros: " + str(fiftyCent))
print("20c-euros: " + str(twentyCent))
print("10c-euros: " + str(tenCent))
print("5c-euros: " + str(fiveCent))
print("2c-euros: " + str(secondCent))
print("1c-euros: " + str(oneCent))