amount = int(input())

twoEuro, rest = divmod(amount, 200)
oneEuro, rest = divmod(rest, 100)
fiftyCent, rest = divmod(rest, 50)
twentyCent, rest = divmod(rest, 20)
tenCent, rest = divmod(rest, 10)
fiveCent, rest = divmod(rest, 5)
secondCent, rest = divmod(rest, 2)
oneCent, rest = divmod(rest, 1)

print("2-euros: " + twoEuro)
print("1-euros: " + oneEuro)
print("50c-euros: " + fiftyCent)
print("20c-euros: " + twentyCent)
print("10c-euros: " + tenCent)
print("5c-euros: " + fiveCent)
print("2c-euros: " + secondCent)
print("1c-euros: " + oneCent)