amount = int(input("Enter the amount of money to be paid (in eurocents)"))

euro_2 = int(amount/200)
amount = amount - (euro_2* 200)
print(euro_2)
euro_1 = int(amount/100)
amount = amount - (euro_1* 100)
print(euro_1)
cent_50 = int(amount/50)
amount = amount - (cent_50 * 50)
print(cent_50)
cent_20 = int(amount/20)
amount = amount - (cent_20 * 20)
print(cent_20)
cent_10 = int(amount/10)
amount = amount - (cent_10 * 10)
print(cent_10)
cent_5 = int(amount/5)
amount = amount - (cent_5 * 5)
print(cent_5)
cent_2 = int(amount/2)
amount = amount - (cent_2 * 2)
print(cent_2)
cent_1 = amount
print(cent_1)