# write your code here int(input("stukken van 1 cent"))
a=int(input("stukken van 1 cent"))
b=int(input("stukken van 2 cent"))
c=int(input("stukken van 5 cent"))
d=int(input("stukken van 10 cent"))
e=int(input("stukken van 20 cent"))
a=float(a*0.01)
b=float(b*0.02)
c=float(c*0.05)
d=float(d*0.1)
e=float(e*0.2)
print("you have "+ str(a+b+c+d+e) + " euro!", sep="")