money = int(input("Give me the amount of money you paid: "))

2euros = money // 200
money -= 2euros
1euros = money // 100
money -= 1 euros
50c = money // 50
money -= money - 50c
20c = money // 20
money -= money - 20c
10c = money // 10
money -= money - 10c
5c = money // 5
money -= money -5c
2c = money // 2
money -= money - 2c
1c = money // 1
printf(%d, 2euros, end="")
printf(%d, 1euros, end="")
printf(%d, 50c, end="")
printf(%d, 20c, end="")
printf(%d, 10c, end="")
printf(%d, 5c, end="")
printf(%d, 2c, end="")
printf(%d, 1c, end="")